/*		Everbrite_DB		*/

CREATE TABLE IF NOT EXISTS MATERIAL(
	MAT_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MAT_NAME VARCHAR(15),
	MAT_DESC VARCHAR(25),
	MAT_COST DOUBLE(7,2),
	MAT_STOCKED BOOLEAN
};

CREATE TABLE IF NOT EXISTS PROCESS(
	PROCESS_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PROCESS_NAME VARCHAR(15),
	PROCESS_WORK_CENTER VARCHAR(15),
	PROCESS_SETUP DOUBLE(4,2),
	PROCESS_RUN_TIME DOUBLE(4,2),
	PROCESS_TOOLING_COST DOUBLE(7,2),
	PROCESS_RATE DOUBLE(4,2)
);

CREATE TABLE IF NOT EXISTS USER_AUTH(
	AUTH_CODE TINYINT(1) UNSIGNED NOT NULL PRIMARY KEY,
	AUTH_NAME VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS DB_USER(
	USER_NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_NAME VARCHAR(15),
	AUTH_CODE TINYINT(1),
	CONSTRAINT AUTH_CODE_FK FOREIGN KEY (AUTH_CODE) REFERENCES USER_AUTH(AUTH_CODE)
);

CREATE TABLE IF EXISTS QUOTE(
	QUOTE_NUM BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PROJ_NUM INT,
	OVER_HEAD_RATE DOUBLE(4,2),
	CUSTOMER VARCHAR(25),
	COMMENT_FIELD VARCHAR(50),
	COMPLETE BOOLEAN,
	COMPLETION_DATE DATE,
	USER_NUM INT,
	CONSTRAINT USER_NUM_FK_1 FOREIGN KEY (USER_NUM) REFERENCES DB_USER(USER_NUM)
);

CREATE TABLE IF NOT EXISTS PROCESS_LINE(
	QUOTE_NUM INT,
	PROCESS_NUM INT,
	CONSTRAINT PROCESS_FK_1 FOREIGN KEY (PROCESS_NUM) REFERENCES PROCESS(PROCESS_NUM),
	CONSTRAINT QUOTE_PROCESS_FK_1 FOREIGN KEY (QUOTE_NUM) REFERENCES QUOTE(QUOTE_NUM)
);

CREATE TABLE IF NOT EXISTS MATERIAL_LINE(
	QUOTE_NUM INT,
	MAT_NUM INT,
	MAT_QTY INT,
	CONSTRAINT MAT_FK_1 FOREIGN KEY (MAT_NUM) REFERENCES MATERIAL(MAT_NUM),
	CONSTRAINT QUOTE_MAT_FK_1 FOREIGN KEY (QUOTE_NUM) REFERENCES QUOTE(QUOTE_NUM)
);
